version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  kartoffel:
    build:
      context: .
      dockerfile: Dockerfile-kartoffel
    container_name: kartoffel
    image: "davidhey/kartoffel"
    depends_on: 
      - mongo
      - redis
    ports:
      - "3000:3000"
  mockserver:
    build:
      context: .
      dockerfile: Dockerfile-mockServer
    container_name: mockserver
    image: "davidhey/mockserver"
    ports:
      - "3001:3001"
  
